"""Registry contract enforcement — see docs/DESIGN.md §3.2.

This module implements `gpufluid blocks --check`. It runs 6 checks:

  1. ID format (re-verified at check time)
  2. Layer declared in DESIGN.md §§4-11
  3. BLOCKS.md row count matches registry
  4. No cross-layer import violations (AST scan)
  5. No duplicate (id, qualname) pairs
  6. Every block has a guard test (warning only)

The folder→layer map and the declared-layer set are PARSED from
DESIGN.md (§2.1 code block, §§4-11 headings) so there is exactly one
source of truth.
"""
from __future__ import annotations
import ast
import importlib
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Set, Tuple

from . import BlockInfo, get_registry, _BLOCK_ID_RE

# ----------------------------------------------------------- paths

_HERE = Path(__file__).resolve()
REPO_ROOT = _HERE.parent.parent.parent.parent
SRC_ROOT = REPO_ROOT / "src" / "gpufluid"
ADDON_ROOT = REPO_ROOT / "addon" / "gpufluid_blender"
DESIGN_MD = REPO_ROOT / "docs" / "DESIGN.md"
BLOCKS_MD = REPO_ROOT / "docs" / "BLOCKS.md"
TESTS_ROOT = REPO_ROOT / "tests"

AUTOGEN_HEADER = (
    "<!-- generated by gpufluid blocks --regen-index; do not edit by hand -->"
)

# Documented layer-import exceptions — see DESIGN.md §3.2.4.1.
# Each entry: (importer_module_prefix, imported_module_prefix) — both relative
# to the `gpufluid` namespace. Wildcards via prefix match (e.g.
# "solvers.solver3d" matches that exact module; "domain" matches all D4).
_KNOWN_LAYER_EXCEPTIONS: List[Tuple[str, str]] = [
    # F3.6 macro closed all 6 historical violations on 2026-05-17:
    #   A1 — domain/sdf math primitives -> primitives/sdf.py (G1)
    #   A2 — domain/mesh_sdf_gpu -> schemes/mesh_marker.py (S2)
    #   B  — domain/animation Motion + evaluate_center -> primitives/animation.py (G1)
    #   C1 — FrameEventQueue + publish_for_frame dual-path added
    #   C2 — solver3d drains queue; domain.regions + domain.seed +
    #         domain.mesh_sdf_gpu entries removed.
    #
    # The list is intentionally empty. A regression test
    # (tests/test_no_layer_exceptions.py — added in F3.6.C3) will
    # guard it from being silently repopulated without an exit plan
    # update in DESIGN.md §3.2.4.1.
]


# ----------------------------------------------------------- report types

@dataclass
class CheckFinding:
    check: int           # 1..6
    code: str            # short tag, e.g. "bad-id-format"
    message: str

    def __str__(self) -> str:
        return f"[check {self.check}/{self.code}] {self.message}"


@dataclass
class CheckReport:
    errors: List[CheckFinding] = field(default_factory=list)
    warnings: List[CheckFinding] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors


# ----------------------------------------------------------- DESIGN.md parsing

_FOLDER_LINE_RE = re.compile(r"^\s*([a-z_]+)/\s+#\s*([A-Z][0-9]+)")
_LAYER_HEADING_RE = re.compile(r"^##\s+\d+(?:\.\d+)?\.?\s+Layer\s+([A-Z][0-9]+)\b")


def parse_folder_map(design_md: Path = DESIGN_MD) -> Dict[str, str]:
    """Parse §2.1 folder→layer map.

    Looks for lines inside the section's code block of the form::

        primitives/            # G1
        schemes/               # S2

    Returns mapping `folder_name -> layer_id`. Raises if the section is
    absent or empty (the contract requires it).
    """
    text = design_md.read_text(encoding="utf-8")
    # Slice from "### 2.1" up to the next heading
    m = re.search(r"### 2\.1[^\n]*\n(.*?)(?=\n## |\n### )",
                  text, flags=re.DOTALL)
    if not m:
        raise RuntimeError("DESIGN.md §2.1 folder map section not found")
    block = m.group(1)
    fmap: Dict[str, str] = {}
    for line in block.splitlines():
        mm = _FOLDER_LINE_RE.match(line)
        if mm:
            fmap[mm.group(1)] = mm.group(2)
    if not fmap:
        raise RuntimeError("DESIGN.md §2.1 folder map parsed empty")
    return fmap


def parse_declared_layers(design_md: Path = DESIGN_MD) -> Set[str]:
    """Return the set of layer IDs declared via `## N. Layer XN — ...`."""
    text = design_md.read_text(encoding="utf-8")
    layers: Set[str] = set()
    for line in text.splitlines():
        m = _LAYER_HEADING_RE.match(line)
        if m:
            layers.add(m.group(1))
    return layers


# ----------------------------------------------------------- module loader

# Folder name → list of (module_basename) we don't try to import directly.
# All loadable modules are auto-discovered by walking the tree.
_SKIP_FILES = {"__init__.py", "__pycache__"}


def _iter_modules(root: Path, package_prefix: str):
    """Yield ('a.b.c', file_path) for every .py under root."""
    for path in sorted(root.rglob("*.py")):
        if any(part in _SKIP_FILES or part.startswith(".")
               for part in path.relative_to(root).parts):
            if path.name != "__init__.py":
                continue
        rel = path.relative_to(root).with_suffix("")
        parts = list(rel.parts)
        if parts[-1] == "__init__":
            parts = parts[:-1]
        mod_name = ".".join([package_prefix] + parts) if parts else package_prefix
        yield mod_name, path


def load_all_modules() -> Tuple[List[str], List[Tuple[str, str]]]:
    """Import every production module so @block decorators fire.

    Returns ``(loaded, failed)``:
      * ``loaded`` — module names successfully imported;
      * ``failed`` — ``(module_name, "ExcType: msg")`` for every module
        skipped on ImportError.

    audit-20260610 (§9.10 — silent fallback): pre-audit the except
    clauses were bare silent ``pass``. When the test harness's bpy stub
    lacked ``mathutils``, all 16 addon modules silently failed to
    import, ZERO A8 blocks registered, and check 3 reported 17 bogus
    "impl-row-without-registry" errors with no hint of the real cause
    (the registry-test failure that exposed this had been latent on
    main). Failures are now collected and returned so callers can be
    loud about them; the test fixture hard-fails on addon failures.
    """
    loaded: List[str] = []
    failed: List[Tuple[str, str]] = []
    # Core package first.
    for mod_name, _ in _iter_modules(SRC_ROOT, "gpufluid"):
        try:
            importlib.import_module(mod_name)
            loaded.append(mod_name)
        except ImportError as e:
            # dodge: optional heavy deps (warp/torch/trimesh) may be absent
            # in a minimal environment — core modules needing them are
            # skipped rather than killing the whole check. Recorded, not
            # silent (§9.10): the caller decides how loud to be.
            failed.append((mod_name, f"{type(e).__name__}: {e}"))
    # Addon — only if bpy is available.
    if "bpy" in sys.modules and ADDON_ROOT.exists():
        # Ensure parent dir is on sys.path so `gpufluid_blender` resolves.
        addon_parent = str(ADDON_ROOT.parent)
        if addon_parent not in sys.path:
            sys.path.insert(0, addon_parent)
        for mod_name, _ in _iter_modules(ADDON_ROOT, "gpufluid_blender"):
            try:
                importlib.import_module(mod_name)
                loaded.append(mod_name)
            except ImportError as e:
                # dodge: an incomplete bpy/mathutils stub must not crash
                # the check tool itself — but a skipped addon module means
                # its A8 blocks never register and check 3 then emits
                # MISLEADING impl-row-without-registry errors. Record so
                # the harness fails on the real cause instead (§9.10).
                failed.append((mod_name, f"{type(e).__name__}: {e}"))
    return loaded, failed


# ----------------------------------------------------------- checks 1, 2, 5

def _check_id_format(registry: Dict[str, List[BlockInfo]],
                     out: CheckReport) -> None:
    for bid in registry:
        if not _BLOCK_ID_RE.match(bid):
            out.errors.append(CheckFinding(
                1, "bad-id-format",
                f"block_id {bid!r} does not match {_BLOCK_ID_RE.pattern}"))


def _check_layer_declared(registry: Dict[str, List[BlockInfo]],
                          declared: Set[str], out: CheckReport) -> None:
    for bid, infos in registry.items():
        layer = infos[0].layer if infos else "?"
        if layer not in declared:
            out.errors.append(CheckFinding(
                2, "layer-not-declared",
                f"{bid} uses layer {layer!r} but it has no `## N. Layer {layer} — ...` "
                f"heading in DESIGN.md. Add the layer to §2 + give it a section."))


def _check_duplicate_qualname(registry: Dict[str, List[BlockInfo]],
                              out: CheckReport) -> None:
    for bid, infos in registry.items():
        seen: Dict[str, BlockInfo] = {}
        for info in infos:
            if info.qualname in seen:
                prev = seen[info.qualname]
                out.errors.append(CheckFinding(
                    5, "duplicate-qualname",
                    f"{bid}: callable {info.qualname!r} registered twice "
                    f"(first at {prev.source_file}:{prev.source_line}, "
                    f"again at {info.source_file}:{info.source_line})"))
            else:
                seen[info.qualname] = info


# ----------------------------------------------------------- check 3 (BLOCKS.md)

# Match a single un-escaped pipe; `\|` is a literal in markdown table cells.
_CELL = r"((?:\\\||[^|])*?)"
_BLOCKS_ROW_RE = re.compile(
    r"^\|\s*" + _CELL + r"\s*\|\s*" + _CELL + r"\s*\|\s*" + _CELL + r"\s*\|\s*"
    + _CELL + r"\s*\|\s*(impl|impl,test|plan)\s*\|"
)


def _parse_blocks_md_rows(blocks_md: Path = BLOCKS_MD) -> List[Tuple[str, str]]:
    """Return list of (block_id, status) parsed from the index table."""
    rows: List[Tuple[str, str]] = []
    for line in blocks_md.read_text(encoding="utf-8").splitlines():
        m = _BLOCKS_ROW_RE.match(line)
        if m:
            rows.append((m.group(1).strip(), m.group(5).strip()))
    return rows


def _check_blocks_md(registry: Dict[str, List[BlockInfo]],
                     out: CheckReport) -> None:
    rows = _parse_blocks_md_rows()
    row_by_id: Dict[str, List[str]] = {}
    for bid, status in rows:
        row_by_id.setdefault(bid, []).append(status)

    # When bpy isn't available, A8.* decorators don't fire — skip checks for
    # those rows so the production check doesn't false-positive on every
    # CLI run outside Blender. The test harness installs a bpy stub.
    bpy_loaded = "bpy" in sys.modules

    # Every BLOCKS.md ID appears exactly once.
    for bid, statuses in row_by_id.items():
        if len(statuses) > 1:
            out.errors.append(CheckFinding(
                3, "duplicate-row",
                f"BLOCKS.md row for {bid} appears {len(statuses)} times "
                f"(statuses: {statuses}). Each block ID must appear at most once."))

    # impl/impl,test rows must have ≥1 registry entry.
    for bid, statuses in row_by_id.items():
        if not bpy_loaded and bid.startswith("A8"):
            continue  # A8 checks gated on bpy availability
        if any(s in ("impl", "impl,test") for s in statuses):
            if bid not in registry or not registry[bid]:
                out.errors.append(CheckFinding(
                    3, "impl-row-without-registry",
                    f"BLOCKS.md marks {bid} as implemented but no @block({bid!r}, ...) "
                    f"decorator was found. Flip the row to `plan` or wire the decorator."))

    # plan rows must have ZERO registry entries.
    for bid, statuses in row_by_id.items():
        if any(s == "plan" for s in statuses):
            if bid in registry and registry[bid]:
                out.errors.append(CheckFinding(
                    3, "plan-row-has-impl",
                    f"BLOCKS.md marks {bid} as `plan` but the registry has "
                    f"{len(registry[bid])} impl(s). Flip the row to `impl` or "
                    f"`impl,test` — run `gpufluid blocks --regen-index`."))

    # Every registered ID has a row.
    for bid in registry:
        if bid not in row_by_id:
            out.errors.append(CheckFinding(
                3, "registry-not-in-blocks-md",
                f"{bid} is registered but absent from BLOCKS.md. "
                f"Run `gpufluid blocks --regen-index`."))


# ----------------------------------------------------------- check 4 (imports)

def _layer_rank(layer: str, declared: Set[str]) -> int:
    """Map 'G1' -> 1, 'S2' -> 2, etc. Returns -1 for undeclared."""
    if layer not in declared:
        return -1
    m = re.match(r"^[A-Z]([0-9]+)$", layer)
    return int(m.group(1)) if m else -1


def _import_layer(import_path: str, folder_map: Dict[str, str]) -> str | None:
    """Resolve `gpufluid.foo.bar` → layer ID of `foo`. None if cross-cutting."""
    parts = import_path.split(".")
    if len(parts) < 2 or parts[0] != "gpufluid":
        return None
    sub = parts[1]
    if sub == "blocks":
        return None  # cross-cutting, exempt
    return folder_map.get(sub)


def _scan_file_imports(path: Path) -> List[str]:
    """Return absolute `gpufluid.<sub>...` imports found in the file."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return []
    imports: List[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            if node.module.startswith("gpufluid"):
                imports.append(node.module)
            elif node.level > 0:
                # Relative import — resolve against file's package.
                rel_root = _file_to_module(path)
                if rel_root:
                    base_parts = rel_root.split(".")[:-node.level]
                    full = ".".join(base_parts + ([node.module] if node.module else []))
                    if full.startswith("gpufluid"):
                        imports.append(full)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith("gpufluid"):
                    imports.append(alias.name)
    return imports


def _file_to_module(path: Path) -> str | None:
    """`src/gpufluid/schemes/foo.py` → `gpufluid.schemes.foo`."""
    try:
        rel = path.relative_to(SRC_ROOT)
    except ValueError:
        return None
    parts = list(rel.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(["gpufluid"] + parts) if parts else "gpufluid"


def _is_whitelisted(importer_mod: str, imported_mod: str) -> bool:
    """True if an importer/imported pair matches an entry in §3.2.4.1."""
    # Both module names are relative to 'gpufluid.' — strip that prefix.
    imp = importer_mod[len("gpufluid."):] if importer_mod.startswith("gpufluid.") else importer_mod
    tgt = imported_mod[len("gpufluid."):] if imported_mod.startswith("gpufluid.") else imported_mod
    for imp_pfx, tgt_pfx in _KNOWN_LAYER_EXCEPTIONS:
        if imp.startswith(imp_pfx) and tgt.startswith(tgt_pfx):
            return True
    return False


def _check_cross_layer_imports(folder_map: Dict[str, str],
                               declared: Set[str],
                               out: CheckReport) -> None:
    for path in sorted(SRC_ROOT.rglob("*.py")):
        try:
            rel_parts = path.relative_to(SRC_ROOT).parts
        except ValueError:
            continue
        # Top-level files (rel_parts has one entry that ends in .py) are the
        # package surface (e.g. __init__.py); cross-cutting, exempt.
        if len(rel_parts) == 1:
            continue
        if rel_parts[0] == "blocks":
            continue  # cross-cutting registry + tooling
        if rel_parts[0] not in folder_map:
            out.errors.append(CheckFinding(
                4, "unmapped-folder",
                f"{path.relative_to(REPO_ROOT)} sits in folder "
                f"{rel_parts[0]!r} which is not in DESIGN.md §2.1 folder map. "
                f"Add it to §2.1 or move the file."))
            continue
        importer_layer = folder_map[rel_parts[0]]
        importer_rank = _layer_rank(importer_layer, declared)
        importer_mod = _file_to_module(path) or ""

        for imp in _scan_file_imports(path):
            imported_layer = _import_layer(imp, folder_map)
            if imported_layer is None:
                continue
            imported_rank = _layer_rank(imported_layer, declared)
            if imported_rank > importer_rank:
                if _is_whitelisted(importer_mod, imp):
                    continue
                out.errors.append(CheckFinding(
                    4, "cross-layer-violation",
                    f"{path.relative_to(REPO_ROOT)} (layer {importer_layer}) "
                    f"imports {imp!r} (layer {imported_layer}). "
                    f"Layer N may only import from layers 1..N-1. If this is "
                    f"intentional, add it to DESIGN.md §3.2.4.1 and to "
                    f"check.py:_KNOWN_LAYER_EXCEPTIONS."))


# ----------------------------------------------------------- check 6 (tests)

def _normalise_id(bid: str) -> str:
    return bid.replace(".", "_").replace("-", "_").lower()


def _slug_in_test_haystack(slug: str, haystack: str) -> bool:
    """True if `slug` appears in the `|`-joined lowercased test-name haystack
    as a COMPLETE block id, not as the numeric prefix of a longer sibling.

    audit-2026-06-14r5 (promoted from the round-4 disputed finding once the
    collisions were confirmed live — 80 of them in the registry): a plain
    ``slug in haystack`` substring test made block ``S2.1`` (slug ``s2_1``)
    count as 'tested' on the strength of any ``test_s2_11_*`` / ``test_s2_14_*``
    function, silently labelling untested blocks impl,test in the STATUS table
    and suppressing their no-guard-test warning.

    The trailing ``(?![0-9])`` lookahead closes the numeric segment so
    ``s2_1`` no longer matches ``s2_11``; the leading ``(?<![a-z0-9])`` keeps
    the head from matching mid-token. A child-block test (``s2_1_gpu``) still
    counts for its parent — that's a refinement of the same block, not a
    different one."""
    return re.search(rf"(?<![a-z0-9]){re.escape(slug)}(?![0-9])",
                     haystack) is not None


def _check_test_coverage(registry: Dict[str, List[BlockInfo]],
                         out: CheckReport) -> None:
    """Warn for any block without a guard test.

    A test "covers" a block when EITHER:
      (a) a `test_*.py` filename or `def test_*` function name contains
          the normalised slug (e.g. `s2_14_6`), OR
      (b) any test file's contents literally mention the block ID
          (e.g. `S2.14.6` in a docstring, comment, or class name).

    Path (b) lets a test exercise a block without requiring its slug to
    appear in the function name — preserves the docs-first principle
    (the test still has to NAME the block to claim coverage) while
    accepting tests that already do via docstrings instead of slugs.
    """
    if not TESTS_ROOT.exists():
        return
    test_files = list(TESTS_ROOT.rglob("test_*.py"))
    slug_haystack: List[str] = []
    full_text_haystack_parts: List[str] = []
    for f in test_files:
        slug_haystack.append(f.stem)
        try:
            txt = f.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        full_text_haystack_parts.append(txt)
        try:
            tree = ast.parse(txt)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
                slug_haystack.append(node.name)
    slug_str = "|".join(slug_haystack).lower()
    full_text = "\n".join(full_text_haystack_parts)
    for bid in registry:
        slug = _normalise_id(bid)
        if _slug_in_test_haystack(slug, slug_str):
            continue
        if bid in full_text:
            continue
        out.warnings.append(CheckFinding(
            6, "no-guard-test",
            f"{bid}: no test names or test file contents mention "
            f"{bid!r} or slug {slug!r}. Add a `[BLK {bid}]` reference "
            f"or rename a test function. Aspirational hygiene — not a CI fail."))


# ----------------------------------------------------------- orchestrator

def run_checks() -> CheckReport:
    """Run all 6 checks and return a report.

    Assumes `load_all_modules()` has already been called by the caller.
    """
    out = CheckReport()
    registry = get_registry()
    try:
        folder_map = parse_folder_map()
    except RuntimeError as e:
        out.errors.append(CheckFinding(
            4, "design-md-parse",
            f"Could not parse DESIGN.md §2.1 folder map: {e}"))
        return out
    declared = parse_declared_layers()

    _check_id_format(registry, out)
    _check_layer_declared(registry, declared, out)
    _check_duplicate_qualname(registry, out)
    _check_blocks_md(registry, out)
    _check_cross_layer_imports(folder_map, declared, out)
    _check_test_coverage(registry, out)
    return out


# ----------------------------------------------------------- regen index

def _read_existing_rows() -> List[Tuple[str, str, str, str]]:
    """Re-read the current BLOCKS.md and return (id, desc, layer, status)
    for every row. Used by regen to preserve rows whose registry entry
    is missing — they get carried over as `plan` (inline-block
    declarations, future-work placeholders, decorators not yet added).
    """
    if not BLOCKS_MD.exists():
        return []
    rows: List[Tuple[str, str, str, str]] = []
    full_row_re = _BLOCKS_ROW_RE
    for line in BLOCKS_MD.read_text(encoding="utf-8").splitlines():
        m = full_row_re.match(line)
        if m:
            rows.append((m.group(1).strip(), m.group(2).strip(),
                         m.group(3).strip(), m.group(5).strip()))
    return rows


def regen_blocks_md() -> str:
    """Render BLOCKS.md content from the current registry + DESIGN.md.

    Caller is responsible for writing the result and calling
    `load_all_modules()` first.

    Preserves existing `plan` rows that have no registry entry — those
    represent inline-block declarations (e.g. G1.4 trilinear weights
    inlined into scatter/sample) and future-work placeholders.
    """
    registry = get_registry()
    declared = parse_declared_layers()
    # Preserve any existing row whose ID isn't in the live registry — flip
    # them to `plan` regardless of what the old status was. The registry is
    # the source of truth for "impl"; if the decorator is missing, the
    # honest status is `plan`. If a decorator is added later, the next
    # regen will flip the row back to `impl`/`impl,test` automatically.
    preserved_plans = [(bid, desc, layer)
                       for (bid, desc, layer, _status) in _read_existing_rows()
                       if bid not in registry]
    # Re-use the layer ordering by numeric rank.
    layer_order = sorted(declared, key=lambda l: _layer_rank(l, declared))

    lines = [
        "# Block index",
        "",
        AUTOGEN_HEADER,
        "",
        "Authoritative auto-generated index of blocks declared in DESIGN.md",
        "(`@block(...)` decorators in `src/`). Run",
        "`gpufluid blocks --regen-index` to refresh.",
        "",
        "Status legend: **impl** = registered via decorator; **impl,test** =",
        "additionally has at least one `test_*` matching the block ID slug;",
        "**plan** = declared in DESIGN.md but not yet registered.",
        "",
        "| ID | Description | Layer | Source location | Status |",
        "|----|-------------|-------|-----------------|--------|",
    ]

    # Compute test coverage map once.
    test_haystack = ""
    if TESTS_ROOT.exists():
        parts: List[str] = []
        for f in TESTS_ROOT.rglob("test_*.py"):
            parts.append(f.stem)
            try:
                tree = ast.parse(f.read_text(encoding="utf-8"))
            except (SyntaxError, UnicodeDecodeError):
                continue
            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
                    parts.append(node.name)
        test_haystack = "|".join(parts).lower()

    def _row_key(bid: str) -> tuple:
        layer = bid.split(".")[0]
        rank = _layer_rank(layer, declared)
        tail = []
        for p in bid.split(".")[1:]:
            try:
                tail.append((0, int(p)))
            except ValueError:
                tail.append((1, p))
        return (rank, layer, tuple(tail))

    def _esc(s: str) -> str:
        # Markdown table cells can't carry literal `|`; escape it so
        # descriptions like `|v|²` round-trip through the parser.
        return s.replace("|", r"\|")

    rendered_ids: Set[str] = set()
    for bid in sorted(registry, key=_row_key):
        infos = registry[bid]
        if not infos:
            continue
        layer = infos[0].layer
        descs = sorted({i.description.split("\n")[0].strip() for i in infos if i.description})
        desc = descs[0] if descs else ""
        if len(infos) > 1:
            desc = (desc + f" ({len(infos)} kernels)").strip()
        src_files = sorted({_short_path(i.source_file) for i in infos})
        src = ", ".join(f"`{s}`" for s in src_files)
        slug = _normalise_id(bid)
        has_test = bool(test_haystack) and _slug_in_test_haystack(slug, test_haystack)
        status = "impl,test" if has_test else "impl"
        lines.append(f"| {bid} | {_esc(desc)} | {layer} | {src} | {status} |")
        rendered_ids.add(bid)

    # Preserve `plan` rows for inline-blocks and future-work placeholders.
    for bid, desc, layer in sorted(preserved_plans, key=lambda r: _row_key(r[0])):
        if bid in rendered_ids:
            continue
        lines.append(f"| {bid} | {desc} | {layer} | — | plan |")

    lines.append("")
    return "\n".join(lines) + "\n"


def _short_path(absfile: str) -> str:
    try:
        return str(Path(absfile).resolve().relative_to(REPO_ROOT)).replace("\\", "/")
    except (ValueError, OSError):
        return absfile


# ----------------------------------------------------------- CLI entry point

def cli_main(argv: List[str]) -> int:
    """Entry point for `gpufluid blocks --check / --regen-index / --list`.

    Returns a process exit code.
    """
    import argparse
    p = argparse.ArgumentParser(prog="gpufluid blocks")
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true",
                   help="verify registry / DESIGN.md / BLOCKS.md / imports")
    g.add_argument("--regen-index", action="store_true",
                   help="rewrite docs/BLOCKS.md from registry")
    g.add_argument("--list", action="store_true",
                   help="pretty-print the registry")
    p.add_argument("--layer", default=None, help="filter --list by layer prefix")
    args = p.parse_args(argv)

    _, failed = load_all_modules()
    if failed:
        # audit-20260610 (§9.10): surface skipped modules loudly — every
        # skip is a module whose blocks did NOT register, which skews
        # check 3/6 results. Not an error by itself (optional deps are
        # legitimate), but never silent again.
        print(f"note — {len(failed)} module(s) skipped on ImportError "
              f"(their @block decorators did NOT fire):")
        for name, err in failed:
            print(f"  {name}: {err}")

    if args.check:
        report = run_checks()
        if report.errors:
            print(f"FAIL — {len(report.errors)} error(s):")
            for e in report.errors:
                print(f"  {e}")
        if report.warnings:
            print(f"warnings ({len(report.warnings)}):")
            for w in report.warnings:
                print(f"  {w}")
        if report.ok and not report.warnings:
            print("OK — registry, DESIGN.md, BLOCKS.md, and layer imports all clean.")
        elif report.ok:
            print(f"OK — no errors. {len(report.warnings)} warning(s).")
        return 0 if report.ok else 1

    if args.regen_index:
        new = regen_blocks_md()
        BLOCKS_MD.write_text(new, encoding="utf-8")
        print(f"wrote {BLOCKS_MD.relative_to(REPO_ROOT)} "
              f"({len(new.splitlines())} lines)")
        return 0

    if args.list:
        from . import by_layer
        registry = get_registry()
        if args.layer:
            items = by_layer(args.layer)
            for info in items:
                print(f"  {info.block_id:14s} {info.qualname}")
        else:
            for bid in sorted(registry):
                infos = registry[bid]
                print(f"  {bid:14s} {len(infos)}x  {infos[0].qualname}")
        return 0

    return 0
