"""Pure-Python translator: scene description (no bpy) → TOML string.

The Bake operator collects bpy state into a plain dict via ``collect_scene``
(in `operators/bake.py`, which DOES import bpy), then passes the dict here.
Keeping this module bpy-free lets us unit-test config generation without
launching Blender.
"""
from __future__ import annotations
from typing import Any, Dict, List, Optional, Tuple


def _fmt_vec3(v):
    return "[%g, %g, %g]" % (float(v[0]), float(v[1]), float(v[2]))


def build_toml(scene_dict: Dict[str, Any]) -> str:
    """Translate a scene dict to a TOML string consumable by `gpufluid simulate`.

    Expected schema (see addon operators.bake.collect_scene)::

        {
            "domain": {"resolution": [nx, ny, nz], "dx": float,
                       "origin": [x, y, z]},          # NOTE: dx & origin are derived
            "fluid": {"lo": [...], "hi": [...], "ppc": int},
            "obstacles": [
                {"type": "sphere", "center": [..], "radius": ..},
                {"type": "box", "center": [..], "half_size": [..]},
                {"type": "cylinder_y", "center": [..], "radius": .., "half_height": ..},
                {"type": "mesh", "path": "..", "scale": .., "translate": [..]},
            ],
            "simulation": {"dt": .., "frames": .., "fps": .., "pressure_iters": ..,
                           "flip_blend": .., "gravity": ..},
            "output": {"cache_dir": "..", "iso_level": .., "smooth_passes": ..,
                       "particles": bool, "preview": bool},
        }

    The simulator works in [0, dom_size] world space anchored at the origin
    given in domain.origin (the addon translates Blender world coords by
    subtracting origin so everything is positive).
    """
    dom = scene_dict["domain"]
    flu = scene_dict.get("fluid")  # legacy single source
    fluids = scene_dict.get("fluids")  # multi-source list (B1.3/B1.4)
    obs = scene_dict.get("obstacles", [])
    sim = scene_dict["simulation"]
    out = scene_dict["output"]

    lines = []
    lines.append("# generated by gpufluid_blender addon")
    lines.append("")
    lines.append("[domain]")
    lines.append(f"resolution = [{int(dom['resolution'][0])}, {int(dom['resolution'][1])}, {int(dom['resolution'][2])}]")
    if "dx" in dom and dom["dx"] is not None:
        lines.append(f"dx = {float(dom['dx']):g}")
    lines.append("")

    def _emit_fluid_body(prefix_lines, f):
        if f.get("kind") == "mesh":
            prefix_lines.append('type = "mesh"')
            esc = f["path"].replace("\\", "\\\\").replace('"', '\\"')
            prefix_lines.append(f'path = "{esc}"')
            prefix_lines.append(f"scale = {float(f.get('scale', 1.0)):g}")
            prefix_lines.append(f"translate = {_fmt_vec3(f.get('translate', [0,0,0]))}")
        else:
            prefix_lines.append('type = "box"')
            prefix_lines.append(f"lo = {_fmt_vec3(f['lo'])}")
            prefix_lines.append(f"hi = {_fmt_vec3(f['hi'])}")
        prefix_lines.append(f"ppc = {int(f.get('ppc', 8))}")
        if "color" in f and f["color"] is not None:
            prefix_lines.append(f"color = {_fmt_vec3(f['color'])}")
        if "temperature" in f and f["temperature"] is not None:
            prefix_lines.append(f"temperature = {float(f['temperature']):g}")

    if fluids:
        for f in fluids:
            lines.append("[[fluids]]")
            _emit_fluid_body(lines, f)
            lines.append("")
    elif flu is not None:
        lines.append("[fluid]")
        _emit_fluid_body(lines, flu)
        lines.append("")
    else:
        raise ValueError("scene_dict needs either 'fluid' or non-empty 'fluids'")
    for o in obs:
        lines.append("[[obstacle]]")
        t = o["type"]
        lines.append(f'type = "{t}"')
        if t == "sphere":
            lines.append(f"center = {_fmt_vec3(o['center'])}")
            lines.append(f"radius = {float(o['radius']):g}")
        elif t == "box":
            lines.append(f"center = {_fmt_vec3(o['center'])}")
            lines.append(f"half_size = {_fmt_vec3(o['half_size'])}")
        elif t == "cylinder_y":
            lines.append(f"center = {_fmt_vec3(o['center'])}")
            lines.append(f"radius = {float(o['radius']):g}")
            lines.append(f"half_height = {float(o['half_height']):g}")
        elif t == "plane":
            lines.append(f"point = {_fmt_vec3(o['point'])}")
            lines.append(f"normal = {_fmt_vec3(o['normal'])}")
            lines.append(f"bbox_lo = {_fmt_vec3(o.get('bbox_lo', [0,0,0]))}")
            lines.append(f"bbox_hi = {_fmt_vec3(o.get('bbox_hi', [1,1,1]))}")
        elif t == "mesh":
            esc = o["path"].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'path = "{esc}"')
            lines.append(f"scale = {float(o.get('scale', 1.0)):g}")
            lines.append(f"translate = {_fmt_vec3(o.get('translate', [0,0,0]))}")
            if "rotate_deg" in o:
                lines.append(f"rotate_deg = {_fmt_vec3(o['rotate_deg'])}")
        else:
            raise ValueError(f"unknown obstacle type: {t}")
        if "motion" in o:
            mt = o["motion"]
            kind = mt["kind"]
            if kind == "linear":
                lines.append(f'motion = {{ kind = "linear", velocity = {_fmt_vec3(mt["velocity"])} }}')
            else:
                raise ValueError(f"unsupported motion kind: {kind}")
        lines.append("")
    # v0.5 inflow / outflow
    for inf in scene_dict.get("inflows", []):
        lines.append("[[inflow]]")
        lines.append(f"lo = {_fmt_vec3(inf['lo'])}")
        lines.append(f"hi = {_fmt_vec3(inf['hi'])}")
        lines.append(f"velocity = {_fmt_vec3(inf.get('velocity', [0,0,0]))}")
        lines.append(f"rate_per_sec = {float(inf.get('rate_per_sec', 5000.0)):g}")
        lines.append(f"frame_start = {int(inf.get('frame_start', 0))}")
        lines.append(f"frame_end = {int(inf.get('frame_end', 1000000))}")
        lines.append("")
    for outr in scene_dict.get("outflows", []):
        lines.append("[[outflow]]")
        lines.append(f"lo = {_fmt_vec3(outr['lo'])}")
        lines.append(f"hi = {_fmt_vec3(outr['hi'])}")
        lines.append(f"frame_start = {int(outr.get('frame_start', 0))}")
        lines.append(f"frame_end = {int(outr.get('frame_end', 1000000))}")
        lines.append("")
    lines.append("[simulation]")
    lines.append(f"dt = {float(sim['dt']):g}")
    lines.append(f"pressure_iters = {int(sim['pressure_iters'])}")
    if "pressure_solver" in sim:
        lines.append(f'pressure_solver = "{sim["pressure_solver"]}"')
    if "cfl" in sim:
        lines.append(f'cfl = {"true" if sim["cfl"] else "false"}')
    if "cfl_factor" in sim:
        lines.append(f'cfl_factor = {float(sim["cfl_factor"]):g}')
    if "cfl_max_substeps" in sim:
        lines.append(f'cfl_max_substeps = {int(sim["cfl_max_substeps"])}')
    if sim.get("reseed"):
        lines.append(f'reseed = true')
        lines.append(f'reseed_every_n_frames = {int(sim.get("reseed_every_n_frames", 5))}')
        lines.append(f'reseed_min_per_cell = {int(sim.get("reseed_min_per_cell", 4))}')
        lines.append(f'reseed_max_per_cell = {int(sim.get("reseed_max_per_cell", 16))}')
    if "surface_tension" in sim:
        lines.append(f"surface_tension = {float(sim['surface_tension']):g}")
    if "csf_smoothing_passes" in sim:
        lines.append(f"csf_smoothing_passes = {int(sim['csf_smoothing_passes'])}")
    lines.append(f"flip_blend = {float(sim['flip_blend']):g}")
    lines.append(f"gravity = {float(sim['gravity']):g}")
    lines.append(f"frames = {int(sim['frames'])}")
    lines.append(f"fps = {int(sim['fps'])}")
    lines.append("")
    lines.append("[output]")
    esc_dir = str(out["cache_dir"]).replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'cache_dir = "{esc_dir}"')
    lines.append(f"mesh = true")
    lines.append(f"iso_level = {float(out['iso_level']):g}")
    lines.append(f"smooth_passes = {int(out['smooth_passes'])}")
    if "mesh_smooth_passes" in out:
        lines.append(f"mesh_smooth_passes = {int(out['mesh_smooth_passes'])}")
    if "mesh_smooth_method" in out:
        lines.append(f'mesh_smooth_method = "{out["mesh_smooth_method"]}"')
    if "decimate_ratio" in out:
        lines.append(f"decimate_ratio = {float(out['decimate_ratio']):g}")
    if "wall_margin_cells" in out:
        lines.append(f"wall_margin_cells = {int(out['wall_margin_cells'])}")
    if "usd" in out:
        lines.append(f"usd = {'true' if out['usd'] else 'false'}")
    lines.append(f"particles = {'true' if out.get('particles', False) else 'false'}")
    lines.append(f"preview = {'true' if out.get('preview', False) else 'false'}")
    if out.get("whitewater"):
        lines.append("whitewater = true")
        for k in ("whitewater_speed_threshold", "whitewater_lifetime_sec",
                  "whitewater_potential_radius", "whitewater_potential_v_max"):
            if k in out:
                lines.append(f"{k} = {float(out[k]):g}")
        for k in ("whitewater_emit_per_frame_max", "whitewater_total_cap"):
            if k in out:
                lines.append(f"{k} = {int(out[k])}")
        if out.get("whitewater_use_potential"):
            lines.append("whitewater_use_potential = true")
    return "\n".join(lines) + "\n"
