"""Pure-Python translator: scene description (no bpy) → TOML string.

The Bake operator collects bpy state into a plain dict via ``collect_scene``
(in `operators/bake.py`, which DOES import bpy), then passes the dict here.
Keeping this module bpy-free lets us unit-test config generation without
launching Blender.

This module is a **dumb serialiser**: it does NOT normalise positions,
unit-convert velocities, or do any physics. All world→[0,1]³ normalisation
happens in bake._collect_scene before the dict reaches us. The single
non-serialisation duty here is deep-merging the optional
`scene_dict["toml_overrides"]` (raw TOML string) over the generated config.
"""
from __future__ import annotations
import sys
from typing import Any, Dict, List, Optional, Tuple

# Round-15 — typed contract + runtime validator. SceneDict is a TypedDict
# (static-only), validate_scene_dict raises SceneDictError with key-path
# on shape mismatch.
#
# Dual-import: relative for normal addon use, file-load fallback for the
# `test_a8_config_builder.py` pattern that loads this file standalone via
# `spec_from_file_location("_gpufluid_config_builder", path)` without a
# parent package. Without the fallback the import line raises
# `ImportError: attempted relative import with no known parent package`
# and breaks the existing pre-round-15 test.
try:
    from .scene_dict import SceneDict, validate_scene_dict, SceneDictError
except ImportError:
    import importlib.util as _ilu
    from pathlib import Path as _Path
    _spec = _ilu.spec_from_file_location(
        "_scene_dict_fallback",
        _Path(__file__).parent / "scene_dict.py",
    )
    _sd = _ilu.module_from_spec(_spec)
    _spec.loader.exec_module(_sd)
    SceneDict = _sd.SceneDict
    validate_scene_dict = _sd.validate_scene_dict
    SceneDictError = _sd.SceneDictError

if sys.version_info >= (3, 11):
    import tomllib  # stdlib
else:  # pragma: no cover
    import tomli as tomllib  # type: ignore


def _fmt_vec3(v):
    return "[%g, %g, %g]" % (float(v[0]), float(v[1]), float(v[2]))


# ---------------------------------------------------------------------------
# FLIP-only simulation fields. Emitted only when sim["solver"] == "flip".
# When solver=="mpm" we instead emit only the [simulation.mpm] subsection
# plus the solver-agnostic timing/gravity/cfl knobs.
# ---------------------------------------------------------------------------
_FLIP_ONLY_SIM_KEYS = (
    "pressure_solver", "pressure_iters", "flip_blend",
    "viscosity_iters", "surface_tension", "csf_smoothing_passes",
    "transfer_mode",
)


def build_toml(scene_dict: SceneDict) -> str:
    """Translate a scene dict to a TOML string consumable by `gpufluid simulate`.

    Round-15: input parameter is typed `SceneDict` (TypedDict) and
    `validate_scene_dict()` is called at entry. Malformed dicts now
    raise `SceneDictError` with the offending key path instead of
    producing ill-typed TOML the CLI silently mishandles.

    Expected schema (see addon operators.bake.collect_scene)::

        {
            "domain": {"resolution": [nx, ny, nz], "dx": float,
                       "origin": [x, y, z]},          # NOTE: dx & origin are derived
            "fluid" | "fluids": ...,
            "obstacles": [...],
            "inflows": [...], "outflows": [...],
            "simulation": {"solver": "flip"|"mpm", ...},
            "output": {...},
            "toml_overrides": "raw TOML string"  # optional; deep-merged last
        }

    All positions in scene_dict are assumed normalised to [0,1]³ (the
    Blender bake operator handles world→unit-cube conversion).
    """
    # Round-15 validator: catch malformed dicts EARLY with key-path
    # error instead of letting them pass through to ill-typed TOML.
    validate_scene_dict(scene_dict)
    dom = scene_dict["domain"]
    flu = scene_dict.get("fluid")  # legacy single source
    fluids = scene_dict.get("fluids")  # multi-source list (B1.3/B1.4)
    obs = scene_dict.get("obstacles", [])
    sim = scene_dict["simulation"]
    out = scene_dict["output"]
    solver = sim.get("solver", "flip")

    lines = []
    lines.append("# generated by gpufluid_blender addon")
    lines.append("")
    lines.append("[domain]")
    lines.append(f"resolution = [{int(dom['resolution'][0])}, {int(dom['resolution'][1])}, {int(dom['resolution'][2])}]")
    if "dx" in dom and dom["dx"] is not None:
        lines.append(f"dx = {float(dom['dx']):g}")
    # FU-016: forward the REAL world extent (metres) so the CLI scales gravity
    # and velocities by metres, not by the resolution aspect-ratio. collect_scene
    # puts DomainTransform.dom_size here.
    if "size_world" in dom and dom["size_world"] is not None:
        sw = dom["size_world"]
        lines.append(
            f"size_world = [{float(sw[0]):g}, {float(sw[1]):g}, {float(sw[2]):g}]")
    lines.append("")

    def _emit_fluid_body(prefix_lines, f):
        if f.get("kind") == "mesh":
            prefix_lines.append('type = "mesh"')
            esc = f["path"].replace("\\", "\\\\").replace('"', '\\"')
            prefix_lines.append(f'path = "{esc}"')
            prefix_lines.append(f"scale = {float(f.get('scale', 1.0)):g}")
            prefix_lines.append(f"translate = {_fmt_vec3(f.get('translate', [0,0,0]))}")
        else:
            prefix_lines.append('type = "box"')
            prefix_lines.append(f"lo = {_fmt_vec3(f['lo'])}")
            prefix_lines.append(f"hi = {_fmt_vec3(f['hi'])}")
        prefix_lines.append(f"ppc = {int(f.get('ppc', 8))}")
        if "color" in f and f["color"] is not None:
            prefix_lines.append(f"color = {_fmt_vec3(f['color'])}")
        if "temperature" in f and f["temperature"] is not None:
            prefix_lines.append(f"temperature = {float(f['temperature']):g}")

    if fluids:
        for f in fluids:
            lines.append("[[fluids]]")
            _emit_fluid_body(lines, f)
            lines.append("")
    elif flu is not None:
        lines.append("[fluid]")
        _emit_fluid_body(lines, flu)
        lines.append("")
    elif not scene_dict.get("inflows"):
        # No static fluid AND no inflow — nothing to seed.
        raise ValueError(
            "scene_dict needs at least one source: 'fluid', 'fluids', or 'inflows'"
        )
    for o in obs:
        lines.append("[[obstacle]]")
        t = o["type"]
        lines.append(f'type = "{t}"')
        if t == "sphere":
            lines.append(f"center = {_fmt_vec3(o['center'])}")
            lines.append(f"radius = {float(o['radius']):g}")
        elif t == "box":
            lines.append(f"center = {_fmt_vec3(o['center'])}")
            lines.append(f"half_size = {_fmt_vec3(o['half_size'])}")
            # Round-59: forward R57's OBB rotation matrix. Pre-R59 this
            # branch silently dropped the rotation key emitted by bake.py
            # (§9.6 mirror drift: bake.py updated to put `rotation` in
            # the obstacle dict, this TOML writer wasn't). Symptom:
            # rotated cube in viewport, fluid still treated it as AABB
            # because scene.toml never carried the rotation.
            if "rotation" in o:
                rows = o["rotation"]
                row_strs = [_fmt_vec3(r) for r in rows]
                lines.append(
                    "rotation = [" + ", ".join(row_strs) + "]"
                )
        elif t == "cylinder_y":
            lines.append(f"center = {_fmt_vec3(o['center'])}")
            lines.append(f"radius = {float(o['radius']):g}")
            lines.append(f"half_height = {float(o['half_height']):g}")
        elif t == "plane":
            lines.append(f"point = {_fmt_vec3(o['point'])}")
            lines.append(f"normal = {_fmt_vec3(o['normal'])}")
            lines.append(f"bbox_lo = {_fmt_vec3(o.get('bbox_lo', [0,0,0]))}")
            lines.append(f"bbox_hi = {_fmt_vec3(o.get('bbox_hi', [1,1,1]))}")
        elif t == "mesh":
            esc = o["path"].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'path = "{esc}"')
            lines.append(f"scale = {float(o.get('scale', 1.0)):g}")
            lines.append(f"translate = {_fmt_vec3(o.get('translate', [0,0,0]))}")
            if "rotate_deg" in o:
                lines.append(f"rotate_deg = {_fmt_vec3(o['rotate_deg'])}")
        else:
            raise ValueError(f"unknown obstacle type: {t}")
        if "motion" in o:
            mt = o["motion"]
            kind = mt["kind"]
            if kind == "linear":
                lines.append(f'motion = {{ kind = "linear", velocity = {_fmt_vec3(mt["velocity"])} }}')
            else:
                raise ValueError(f"unsupported motion kind: {kind}")
        lines.append("")
    # v0.5 inflow / outflow
    for inf in scene_dict.get("inflows", []):
        lines.append("[[inflow]]")
        lines.append(f"lo = {_fmt_vec3(inf['lo'])}")
        lines.append(f"hi = {_fmt_vec3(inf['hi'])}")
        lines.append(f"velocity = {_fmt_vec3(inf.get('velocity', [0,0,0]))}")
        lines.append(f"rate_per_sec = {float(inf.get('rate_per_sec', 5000.0)):g}")
        lines.append(f"frame_start = {int(inf.get('frame_start', 0))}")
        lines.append(f"frame_end = {int(inf.get('frame_end', 1000000))}")
        # B18 — optional per-inflow attributes. Only emitted when the addon
        # set them (zero-overhead path for scenes that don't use colour).
        if inf.get("color") is not None:
            lines.append(f"color = {_fmt_vec3(inf['color'])}")
        if inf.get("temperature") is not None:
            lines.append(f"temperature = {float(inf['temperature']):g}")
        kfs = inf.get("keyframes") or []
        if kfs:
            # Emit one row per keyframe: [frame, lo_x, lo_y, lo_z, hi_x, hi_y, hi_z]
            lines.append("keyframes = [")
            for r in kfs:
                lines.append(
                    "  [%d, %g, %g, %g, %g, %g, %g],"
                    % (int(r[0]), float(r[1]), float(r[2]), float(r[3]),
                       float(r[4]), float(r[5]), float(r[6]))
                )
            lines.append("]")
        lines.append("")
    for outr in scene_dict.get("outflows", []):
        lines.append("[[outflow]]")
        lines.append(f"lo = {_fmt_vec3(outr['lo'])}")
        lines.append(f"hi = {_fmt_vec3(outr['hi'])}")
        lines.append(f"frame_start = {int(outr.get('frame_start', 0))}")
        lines.append(f"frame_end = {int(outr.get('frame_end', 1000000))}")
        lines.append("")
    lines.append("[simulation]")
    lines.append(f'solver = "{solver}"')
    # Solver-agnostic timing knobs always go in.
    lines.append(f"dt = {float(sim['dt']):g}")
    if "cfl" in sim:
        lines.append(f'cfl = {"true" if sim["cfl"] else "false"}')
    if "cfl_factor" in sim:
        lines.append(f'cfl_factor = {float(sim["cfl_factor"]):g}')
    if "cfl_max_substeps" in sim:
        lines.append(f'cfl_max_substeps = {int(sim["cfl_max_substeps"])}')
    lines.append(f"gravity = {float(sim['gravity']):g}")
    lines.append(f"frames = {int(sim['frames'])}")
    lines.append(f"fps = {int(sim['fps'])}")
    # FLIP-only pressure/transfer/viscosity knobs. Reseed kept under its own
    # `reseed` toggle (works for both solvers, no harm leaving as-is).
    if solver == "flip":
        if "pressure_iters" in sim:
            lines.append(f"pressure_iters = {int(sim['pressure_iters'])}")
        if "pressure_solver" in sim:
            lines.append(f'pressure_solver = "{sim["pressure_solver"]}"')
        if "flip_blend" in sim:
            lines.append(f"flip_blend = {float(sim['flip_blend']):g}")
        if "viscosity_iters" in sim:
            lines.append(f"viscosity_iters = {int(sim['viscosity_iters'])}")
        if "surface_tension" in sim:
            lines.append(f"surface_tension = {float(sim['surface_tension']):g}")
        if "csf_smoothing_passes" in sim:
            lines.append(f"csf_smoothing_passes = {int(sim['csf_smoothing_passes'])}")
        if "transfer_mode" in sim:
            lines.append(f'transfer_mode = "{sim["transfer_mode"]}"')
    if sim.get("reseed"):
        lines.append(f'reseed = true')
        lines.append(f'reseed_every_n_frames = {int(sim.get("reseed_every_n_frames", 5))}')
        lines.append(f'reseed_min_per_cell = {int(sim.get("reseed_min_per_cell", 4))}')
        lines.append(f'reseed_max_per_cell = {int(sim.get("reseed_max_per_cell", 16))}')
    # MPM-specific knobs (B17.12 / F3.7 / S2.17.*). Only emitted when solver=mpm.
    if solver == "mpm":
        lines.append("")
        lines.append("[simulation.mpm]")
        for key in ("bulk_modulus", "rpic_damping", "grid_v_damping",
                    "cube_friction", "v_terminal", "vz_max_splash",
                    "initial_velocity"):
            full_key = f"mpm_{key}"
            if full_key in sim:
                lines.append(f"{key} = {float(sim[full_key]):g}")
    lines.append("")
    lines.append("[output]")
    esc_dir = str(out["cache_dir"]).replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'cache_dir = "{esc_dir}"')
    lines.append(f"mesh = true")
    lines.append(f"iso_level = {float(out['iso_level']):g}")
    lines.append(f"smooth_passes = {int(out['smooth_passes'])}")
    if "mesh_smooth_passes" in out:
        lines.append(f"mesh_smooth_passes = {int(out['mesh_smooth_passes'])}")
    if "mesh_smooth_method" in out:
        lines.append(f'mesh_smooth_method = "{out["mesh_smooth_method"]}"')
    if "decimate_ratio" in out:
        lines.append(f"decimate_ratio = {float(out['decimate_ratio']):g}")
    if "wall_margin_cells" in out:
        lines.append(f"wall_margin_cells = {int(out['wall_margin_cells'])}")
    if "usd" in out:
        lines.append(f"usd = {'true' if out['usd'] else 'false'}")
    lines.append(f"particles = {'true' if out.get('particles', False) else 'false'}")
    lines.append(f"preview = {'true' if out.get('preview', False) else 'false'}")
    # B18.5 — per-vertex colour mixing mode for the mesher.
    if out.get("color_mix_mode") and out["color_mix_mode"] != "linear":
        lines.append(f'color_mix_mode = "{out["color_mix_mode"]}"')
    if out.get("whitewater"):
        lines.append("whitewater = true")
        # Round-23: added `whitewater_trapped_air_weight`. It was in
        # scene_dict + CLI config (commands.py:723 `alpha`) but missing
        # from this emit loop — addon user could not tune trapped-air
        # potential weight; CLI always defaulted to 1.0 silently.
        for k in ("whitewater_speed_threshold", "whitewater_lifetime_sec",
                  "whitewater_potential_radius", "whitewater_potential_v_max",
                  "whitewater_trapped_air_weight",
                  "whitewater_wave_crest_weight"):
            if k in out:
                lines.append(f"{k} = {float(out[k]):g}")
        for k in ("whitewater_emit_per_frame_max", "whitewater_total_cap"):
            if k in out:
                lines.append(f"{k} = {int(out[k])}")
        if out.get("whitewater_use_potential"):
            lines.append("whitewater_use_potential = true")

    generated = "\n".join(lines) + "\n"

    overrides = (scene_dict.get("toml_overrides") or "").strip()
    if not overrides:
        return generated

    # Parse both, deep-merge, re-serialise via minimal emitter.
    try:
        base_dict = tomllib.loads(generated)
        override_dict = tomllib.loads(overrides)
    except tomllib.TOMLDecodeError as e:
        # Re-raise as ValueError so the bake operator's existing handler picks
        # it up (config_builder is bpy-free; no self.report here).
        raise ValueError(f"TOML overrides parse error: {e}") from e
    merged = _deep_merge(base_dict, override_dict)
    return _emit_toml(merged)


def _deep_merge(base: Dict[str, Any], over: Dict[str, Any]) -> Dict[str, Any]:
    """Recursive merge — over wins on scalar conflicts; lists are replaced
    wholesale (TOML semantics); nested tables merge field-by-field."""
    out = dict(base)
    for k, v in over.items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


# ---------------------------------------------------------------------------
# Minimal TOML emitter — handles scalars (str/int/float/bool), homogeneous
# lists, inline tables, nested tables, and arrays of tables. Sufficient for
# the gpufluid scene schema.
# ---------------------------------------------------------------------------

import math as _math


def _emit_scalar(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        # Round-7 reviewer flag: raw f"{v:g}" emits "inf" / "nan" which
        # tomllib parses as a literal token and chokes. Reject early
        # with a clear message — caller (probably a PropertyGroup default
        # that wasn't initialised) needs to know which value is bad.
        if _math.isnan(v) or _math.isinf(v):
            raise ValueError(f"non-finite float in TOML: {v!r}")
        return f"{v:g}"
    if isinstance(v, str):
        esc = v.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{esc}"'
    if isinstance(v, (list, tuple)):
        # Detect list-of-lists (e.g. inflow.keyframes) — emit multi-line for
        # readability; flat list otherwise.
        if v and all(isinstance(x, (list, tuple)) for x in v):
            inner = ",\n  ".join(_emit_scalar(x) for x in v)
            return f"[\n  {inner},\n]"
        return "[" + ", ".join(_emit_scalar(x) for x in v) + "]"
    if isinstance(v, dict):
        # Inline table. Round-8 reviewer flag: previously bare
        # _emit_scalar(val) lost the inner key on error — a non-finite
        # float in `{ kind = "linear", velocity = inf }` raised
        # "non-finite float in TOML: inf" with no breadcrumb to
        # `velocity`. Wrap each pair so the error names the inner key.
        parts = []
        for k, val in v.items():
            try:
                inner = _emit_scalar(val)
            except ValueError as e:
                raise ValueError(f"inline-table key '{k}': {e}") from None
            parts.append(f"{k} = {inner}")
        return "{ " + ", ".join(parts) + " }"
    # Reviewer flag: None used to raise this generic ValueError without
    # pointing at the key, leaving the caller debugging a 4000-line
    # scene_dict. Caller (_emit_table) now wraps this with key context.
    raise ValueError(f"unsupported TOML value: {v!r} ({type(v).__name__})")


def _is_table(v: Any) -> bool:
    return isinstance(v, dict)


def _is_array_of_tables(v: Any) -> bool:
    return isinstance(v, list) and len(v) > 0 and all(isinstance(x, dict) for x in v)


def _emit_table(out_lines: List[str], path: str, table: Dict[str, Any]) -> None:
    """Emit a [path] table. Scalars first, then nested arrays-of-tables and
    sub-tables."""
    if path:
        out_lines.append(f"[{path}]")
    scalars = {}
    sub_tables = {}
    sub_arrays = {}
    for k, v in table.items():
        if _is_array_of_tables(v):
            sub_arrays[k] = v
        elif _is_table(v):
            sub_tables[k] = v
        else:
            scalars[k] = v
    # Wrap each _emit_scalar with key context so non-finite floats /
    # unsupported types point at the actual scene_dict key the user (or
    # an override) screwed up, instead of a bare ValueError(repr(v)).
    def _emit_with_key(k, v, prefix=""):
        try:
            return _emit_scalar(v)
        except ValueError as e:
            full = f"{prefix}{k}" if prefix else (
                f"{path}.{k}" if path else k)
            raise ValueError(f"TOML emit failed at '{full}': {e}") from None

    for k, v in scalars.items():
        out_lines.append(f"{k} = {_emit_with_key(k, v)}")
    if path:
        out_lines.append("")
    for k, sub in sub_tables.items():
        sub_path = f"{path}.{k}" if path else k
        _emit_table(out_lines, sub_path, sub)
    for k, arr in sub_arrays.items():
        sub_path = f"{path}.{k}" if path else k
        for i, entry in enumerate(arr):
            out_lines.append(f"[[{sub_path}]]")
            prefix = f"{sub_path}[{i}]."
            # Round-10 fix (data-loss bug from BACKLOG): include
            # dict-valued fields as inline-tables, not just scalars.
            # Pre-fix code filtered them out → motion = {...} on an
            # obstacle entry was silently dropped from the overrides-
            # merged TOML output. _emit_scalar already handles dict as
            # inline-table; just don't exclude it here.
            for kk, vv in entry.items():
                if _is_array_of_tables(vv):
                    # Nested array-of-tables inside an entry — not used
                    # by current scene_dict. Log explicitly so a future
                    # schema change doesn't silently lose them.
                    out_lines.append(
                        f"# WARNING: nested [[..]] in {prefix}{kk} dropped "
                        f"(_emit_table doesn't handle this case)")
                    continue
                out_lines.append(f"{kk} = {_emit_with_key(kk, vv, prefix)}")
            out_lines.append("")


def _emit_toml(d: Dict[str, Any]) -> str:
    lines: List[str] = ["# generated by gpufluid_blender addon (merged with overrides)"]
    lines.append("")
    _emit_table(lines, "", d)
    # Trim trailing blank lines, ensure single newline at EOF.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"
